### ISSUE TITLE
Get DNS set up properly

### ISSUE THREAD

**Issue by morganastra** [witch-house/pronoun.is#1]
Currently it's just redirecting from pronoun.is to pronouns.herokuapp.com, but we want pronoun.is to actually stay in the URL bar when people visit the site

**Comment by morganastra** [comment]
Wow I guess we have to get isnic to point at dns servers we control, then we have to configure those dns servers CNAME records to point to Heroku.

https://devcenter.heroku.com/articles/custom-domains

Not immediately relevant, but why doesn't Heroku just run their own nameservers?

**Comment by thelseraphim** [comment]
morgan did it, hell yeah
