### ISSUE TITLE
license

### ISSUE THREAD

**Issue by thelseraphim** [witch-house/pronoun.is#11]
another pretentious thing but let's put a good license on it, why not.

**Comment by thelseraphim** [comment]
@morganastra what should we use? I vote for NOT gpl, some kind of dgaf license

**Comment by morganastra** [comment]
I'd go with CC0, but it has gender binarist "his or her" language, which seems especially innappropriate for this website. Let's go with the WTFPL.

**Comment by morganastra** [comment]
Actually the WTFPL maybe not a good fit either, https://twitter.com/mcclure111/status/664288320575381504. Reopening to think about

**Comment by TazeTSchnitzel** [comment]
Affero GNU General Public License. The strongest form of GPL.

**Comment by Pawtiko** [comment]
How about the [Unlicence](http://unlicense.org/)?

**Comment by TazeTSchnitzel** [comment]
If we were to go that route I'd be more confident in CC0.

**Comment by morganastra** [comment]
I've done a lot of thinking about this and come around to the idea that even simple things like pronoun.is that are very unlikely to be co-opted by corporations should still have the protections of the GPL. Conveniently, the GPL won't misgender the users or authors!

bodil has a really good thread on this: https://twitter.com/bodil/status/777196820015509505
