### ISSUE TITLE
Change the page background color to something more gender-neutral

### ISSUE THREAD

**Issue by ajrezin** [witch-house/pronoun.is#120]
Not related to a specific problem, I just think it would be great if the site background was a little more gender neutral! Green or yellow perhaps? 

**Additional context**
This is a simple one-line change in the CSS file, I can open a PR if this is something you're willing to consider!

**Comment by clarfonthey** [comment]
Disagree that colours have gender, but perhaps there could be a beige and green colour scheme to fit with an island theme.

**Comment by arimgibson** [comment]
+1 what Clar said, colors only have gender if we give em a gender 😊 I like the idea of an island theme though!

**Comment by morganastra** [comment]
All colors are gender neutral :) The pink color is meant to evoke a retro 80s sunset motif (which has ironically come way back into fashion in the time since our CSS was originally written!)
