### ISSUE TITLE
They/Them is in the pronoun table twice.

### ISSUE THREAD

**Issue by tacosontitan** [witch-house/pronoun.is#135]
Simply put, they/them is in the pronoun table twice:

![Screenshot of the duplicate table entries.](https://user-images.githubusercontent.com/65432314/129488168-8b6021ca-bc87-4524-ac6b-267157a788ed.png)

**Comment by arimgibson** [comment]
Yep, that's because one is for people who use the reflexive "themselves" vs the reflexive "themself". It's a tiny detail, i almost missed it at first too!

**Comment by tacosontitan** [comment]
> Yep, that's because one is for people who use the reflexive "themselves" vs the reflexive "themself". It's a tiny detail, i almost missed it at first too!

Oh great catch! 😄 In that case, we can close this issue.

**Comment by clarfonthey** [comment]
Maybe rearranging the table so they're both next to each other might make this more clear?

**Comment by arimgibson** [comment]
I sorta like that idea, although my best guess for why they were separated was to order them by popularity. I think i like that approach better, but just my thoughts :)
