### ISSUE TITLE
do we need to think more about multilingual situations

### ISSUE THREAD

**Issue by thelseraphim** [witch-house/pronoun.is#14]
Our site doesn't do it, but can we acknowledge that gracefully?

**Comment by non** [comment]
It might be nice to have a FAQ page where a question about non-English pronouns could go.

For example, it could link to: https://en.wikipedia.org/wiki/Gender_neutrality_in_languages_with_grammatical_gender

**Comment by Farthen** [comment]
Would there be any interest in a multilingual solution? Like, when someone would do a pull request that adds support for a different language, would you be interested?

**Comment by morganastra** [comment]
Depending on how well it integrates with the rest of the site - for example we have a nice pun we have in the URL which is English-specific. For a site this simple it might make more sense to just fork it for different languages.
