### ISSUE TITLE
font rendering problem on windows

### ISSUE THREAD

**Issue by inklesspen** [witch-house/pronoun.is#22]
A friend of mine reported bad font rendering on Chrome on Windows 7.
![example](http://i.imgur.com/hlparbx.png)

However, if ve zooms in, apparently it's fine.

I inquired, and ve does have Futura installed, and thinks it's a legit version, not something from a free font site.

**Comment by morganastra** [comment]
I don't use windows, so I have no way to reproduce. I'd be happy to accept a PR of course.

**Comment by inklesspen** [comment]
I don't use Windows either, and I'm not a designer, but I don't think there's any solution other than picking different fonts, at least for Windows machines.

I'd suggest actually picking a font available from Google's web fonts and using that. I like the look of [Lato](https://www.google.com/fonts/specimen/Lato), personally.

You could start using it by adding this to your html HEAD and stylesheet.
```html
<link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
```

```css
body {
	font-family: font-family: 'Lato', sans-serif;
	background-color: #F6CEFC;
}
```

**Comment by TazeTSchnitzel** [comment]
Chrome of Windows seems to have a general problem with horrific font rendering.

**Comment by morganastra** [comment]
this issue is stale and there is no indication it extends beyond one anecdotal windows computer. closing.
