### ISSUE TITLE
Multiple pronouns

### ISSUE THREAD

**Issue by corajr** [witch-house/pronoun.is#25]
I'd appreciate being able to specify several alternatives for pronouns, and I imagine others would as well. I'm happy to make a pull request for this, just wanted to get feedback on some different options for the URL before jumping in!

Some possibilities I thought of:

pronoun.is/either?ze/zem,they
pronoun.is/either/they/she
pronoun.is?any_of=he,ze/hir

**Comment by morganastra** [comment]
In the interest of keeping our url scheme simple and easy to understand I think we should only support one set of pronouns per url. People are of course free to use two separate links for separate pronoun sets.
