### ISSUE TITLE
let "them" folks concisely choose "themself" vs "themselves"

### ISSUE THREAD

**Issue by idupree** [witch-house/pronoun.is#46]
I think "themself" is more popular for gender-neutral people. People who describe themselves as plural[1] often are "themselves".

Right now, "themself" users can write https://pronoun.is/they/them/their/theirs/themself while "themselves" users can write https://pronoun.is/they .  We (some friends I'm talking to) would like to write https://pronoun.is/they/themself or https://pronoun.is/they/themselves to specify which.  (not sure which default is best).

I guess the way to do this is add a "they them their theirs themself" line in https://github.com/witch-house/pronoun.is/blob/master/resources/pronouns.tab and then edit the Clojure code to search in more ways for matching pronoun sets?

This may or may not interact with https://github.com/witch-house/pronoun.is/issues/38 . probably not.

[1] in case you're not familiar, this sort of thing http://healthymultiplicity.com/

**Comment by morganastra** [comment]
thanks for filing this issue. I've been thinking about how to support both singular vs plural forms myself and it's definitely a feature I want. I think the right way to do that is to allow people to write "pronoun.is/they/themselves" like you said, or even just "pronoun.is/themselves", but the precise design is not fully-baked yet. One problem with both of those is they break with the current practice of using "subject" or "subject/object" forms, as is conventional in English.

> I think "themself" is more popular for gender-neutral people.

In my experience and among friends I've casually asked, "themselves" seems more popular even for singlets (people who are not part of a plural system), but it sounds like we're both judging by anecdote! It would be great to see a poll of people who use they (I'll put an informal one on twitter, at least)

**Comment by morganastra** [comment]
Poll results here: https://twitter.com/morganastra/status/745800591125798912

This is, of course, not a study with any amount of scientific rigor whatsoever, but it's the best I know how to do for now. Of 515 votes, 44% of people who use they prefer "themselves", 28% prefer "themself", and 28% have no preference. Based on that (anec)data I believe it's correct to leave "themselves" as the default reflexive form.

(I still agree there should be a way to explicitly choose the "themself" form)

**Comment by morganastra** [comment]
okay now that we use query parameters for something (multi pronouns, see #38), we can use it everywhere! what do you think about having an url like `pronoun.is/they?reflexive=themself`?

**Comment by bugQ** [comment]
As author of #30 this looks like a sufficiently elegant solution.

**Comment by ardnaxelarak** [comment]
I've started taking a look at this, but there could be some weird interactions between this and `or`--I think the intended behavior is fairly clear (`pronoun.is/they?reflexive=themself&or=she` is they/themself and she/her, whereas `pronoun.is/she?or=they&reflexive=themself` is the same) but this would require a tricky bit of determining order of params and in the worst case, someone could have something like `pronoun.is/they?reflexive=themself&or=she&or=they&reflexive=themselves` which would be even trickier, if not impossible, to parse.

**Comment by morganastra** [comment]
@ardnaxelarak it is trivial to match reflexives to their corresponding objects pronouns, since they'll both occur in the same line. it makes no sense to use a reflexive declension of one pronoun with a subject declension of another so we do not need to support that usecase. thus even `pronoun.is/they?or=she&reflexive=themselves` unambiguously denotes "they/.../themselves" and "she/her" pronouns.

**Comment by idupree** [comment]
My reservation about `?reflexive=` is that it's a fancy grammar word.  I like fancy grammar words, but I also like the aesthetic of pronoun.is where I don't have to think about them.

~~

What about changing util.clj's `table-lookup` to match pronouns more loosely:

```
(defn table-lookup
  [query-key table]
  (let [filtered-table (filter #(clojure.set/subset?
                                  (into #{} query-key) (into #{} %))
                                table)]
    (first filtered-table)))
```
and adding `they them their theirs themself` to pronouns.tab*

For example, pronoun.is/themself would work, or pronoun.is/they/themself, or more questionably pronoun.is/him/he would work too.  (I could change this not to match reversed order of pronoun forms, if that seems better.)

Caveat, this is my first clojure code and I only tested it in an online REPL yet.  If clojure.set operations are not idiomatic, it could use `every?`/`some` here, I think.

\*  (after the `themselves` line, because your poll says `themselves` should be the default)

**Comment by j-po** [comment]
What about `plural=1`? Like, for some pronouns it may well be a noop, but it's concise and, I think, clear.

**Comment by bugQ** [comment]
@idupree's solution seems like the best, and makes it easier to add a wider variety of variants to other pronoun sets, too.  Presumably the syntax for supplying a completely custom pronoun remains the same, i.e., they must be specified in order, but this would allow nice shortcuts for pronouns that are in the list, such as pronoun.is/xyr or pronoun.is/themself.

**Comment by TazeTSchnitzel** [comment]
`/them////themselves`?

**Comment by morganastra** [comment]
multiple slashes without path elements between them are semantically
equivalent to a single slash.

what if we allowed e.g. `/them/.../themselves`?

**Comment by TazeTSchnitzel** [comment]
Yeah, that was my second thought. (I edited the comment to add it, even, but you don't get emailed for that.)

another possibility is `/them/*/themselves`, though having `*` represent multiple items feels wrong.

**Comment by morganastra** [comment]
well, great minds think alike I suppose. I like the ellipses, and it's implemented with them in 5d85c1a

**Comment by morganastra** [comment]
this feature isn't done yet, though, because `minimum-unambiguous-path` doesn't know how to use ellipses so the front page looks really ugly right now

**Comment by bugQ** [comment]
ellipses (preferably three periods, and not U+2026) make sufficient sense.  another convention is `**`, which is used in some file path pattern matching (a.k.a. "glob") systems to denote arbitrary depth.
