### ISSUE TITLE
First person pronouns

### ISSUE THREAD

**Issue by nfearnley** [witch-house/pronoun.is#62]
Might you consider adding first person pronouns to the database?

I was trying to use the site to demonstrate the we/us/our/ours/ourselves first person pronouns of this character: http://questionablecontent.net/view.php?comic=3393

I was able to do it but had to manually enter each of the pronouns. It might make sense to include personal pronouns in the database for future use. If this is outside of the scope of your project, I understand and respect your decision.

**Comment by morganastra** [comment]
currently the scope of pronoun.is is defined to include only third-person personal pronouns. one barrier to adding first-person pronouns is that we would have to re-write the example sentences, which are at this point quite recognizable. it might happen at some point in the future, but probably not any time soon
