### ISSUE TITLE
Internationalization?

### ISSUE THREAD

**Issue by garbados** [witch-house/pronoun.is#66]
It'd be great to use pronoun.is to communicate pronouns in languages other than English!

**Comment by garbados** [comment]
I'd love to help with this, but I've never approached the problem within a Clojure project, so I'm a little out of my depth. Let me know if there's anything I can do to help!

**Comment by pazzjurist** [comment]
The use of the clojure language for this is interesting, but surely it can be done. I see pull reqs dating back to months ago that have gone unanswered. I'd be able to assist as well but if the maintainer doesn't answer anything, it is a lost cause.

**Comment by morganastra** [comment]
You actually wouldn't really need to know clojure to translate the project; the code would stay the same, only the words would change. To the extent you'd need any help with that I would be happy too, but English is the only language I am comfortable enough in to create a site like this for. I am in general very supportive of the idea of having versions for other languages, but I think they should have their own domains names (ideally with a clever TLD pun like pronoun.is has for english!)

The first discussion of this happened in #13 and #14

**Comment by morganastra** [comment]
Since this question has come up a few times I think it might be a good idea to add something to the README about it

**Comment by morganastra** [comment]
https://github.com/witch-house/pronoun.is#can-we-translate-pronounis-into-another-language
