### ISSUE TITLE
Allow pronoun.is/they/or/xe/xir/or/she 

### ISSUE THREAD

**Issue by lynn** [witch-house/pronoun.is#69]
This syntax is far friendlier than `/they?or=xe/xir&or=she`, I think. I don't suppose anyone uses the English connective *or* as a pronoun, so splitting on `or`s should be fine.

**Comment by lynn** [comment]
#70 implements this, while still allowing the old syntax.

**Comment by morganastra** [comment]
hey Lynn thanks for submitting this.

> This syntax is far friendlier than `/they?or=xe/xir&or=she`

I'm not really sure I agree that that's true; "or" isn't visually distinct at all, it's hard to tell at a glance what is happening there (while the parameter punctuation, in addition to making our URLs act a little more like one might expect URLs to act, makes it quite visually apparent that there is a second set of pronouns). Which is not to say I'm categorically rejecting this proposal but, if you feel strongly about this could you elaborate on why you think it's better?

**Comment by lynn** [comment]
I wanted to make the syntax more accessible for people who don’t know HTML query strings. If you aren’t a programmer, the mix of `?`s and `&`s and `/`s is not semantically meaningful or helpful at all; it looks like dark magic and it’s very easy to get wrong. You might type `/they&or=xe/xir?or=she` into your Twitter bio and you might get frustrated not knowing why it doesn’t work.

The `pronoun.is/they/or/xe/xir/or/she` syntax is clearer to me personally: I can read it as a string of words, and find it easier to mentally split over the word “or” than to mentally split over some strange ASCII junk. I also think it looks prettier in a bio. That said, I don’t think keeping both syntaxes hurts anyone.

Finally, when I proposed the new syntax on Twitter, it got [7 likes](https://twitter.com/chordbug/status/870977584452046848), so that counts for something, right?! :)

**Comment by pazzjurist** [comment]
This would be very useful.

**Comment by morganastra** [comment]
I hear the desire for a smoother/less technical/harder to mess up way to write urls with multiple pronouns sets, but whatever approach we use needs to be visually and syntactically distinct from a path. I'm marking this as "needs design" for now.

I wonder if just having a good pronoun selector page would obviate the need for this?

**Comment by lynn** [comment]
> whatever approach we use needs to be visually and syntactically distinct from a path.

I don't see what's wrong with treating `/or/` as a new syntax element in paths, just as pronoun.is has already repurposed `/.../`.

"Visually distinct" is a matter of personal taste, and it feels like you're holding yours over mine or @pazzjurist's or my Twitter friends'. 

It's a little disheartening to have gone out of my way to contribute to this project, be made to defend my change, and then have my defense met with months of silence followed by "I don't like it" :( I don't know what else to do. The only compromise I can think of is `pronoun.is/they//xe/xir//she`. But it's semantically weird and I still prefer `/or/`.

Regarding your last point, I think the URLs should be easy for everyone to read/write/adapt without having to visit pronoun.is for more information/a selector page (that's actually a *feature* to me).

**Comment by wakest** [comment]
quite agree with @lynn's idea, I was confused by the /.../ links on the front page and was coming here to the github specifically to see if there was other syntax available to use. if you wanted the or to visually stand out more you could require it to be a capital 'OR' so it looks more like a selector, though I don't know how clean that looks.

**Comment by morganastra** [comment]
we now support this - e.g. https://pronoun.is/they/:or/she
