### ISSUE TITLE
pronoun.is allows duplicate or's

### ISSUE THREAD

**Issue by Avizc** [witch-house/pronoun.is#75]
Currently right now when you request for pronouns you can duplicate your request.

Example:
`http://pronoun.is/he/?or=he&or=he`
![he/he/he](https://i.imgur.com/arhZFrh.png)

`http://pronoun.is/he/?or=he&or=ze`
![he/he/ze](https://i.imgur.com/NNPEIc2.png)

I believe this is where the issue lies: `pronoun.is/src/pronouns/pages.clj` with the following code where it's allowing this maybe? I think:
```
(defn pronouns [params]
  (let [path (params :*)
        alts (or (params "or") [])
        pronouns (concat [path] (u/vec-coerce alts))
        pronoun-declensions (filter some? (map #(lookup-pronouns
                                                 (escape-html %))
                                               pronouns))]
    (if (seq pronoun-declensions)
      (format-pronoun-examples pronoun-declensions)
      (not-found))))
```
I haven't done clojure before so I'm unsure if this would be the fix for that or not:
```
alts (distinct (params "or") [])
;; or
alts (or (distinct (params "or") []))
;; or something else?
```
I'd be happy to make a pull request if that's the fix! Either way I think this project is really cute and it makes me happy to see on Twitter a lot. Thank you so much for doing this.

**Comment by morganastra** [comment]
i don't really think this is a bug
