### ISSUE TITLE
Show pronunciation of pronouns

### ISSUE THREAD

**Issue by cybrosa** [witch-house/pronoun.is#80]
As it is currently:

> Xey went to the park.

How is that word pronounced? Is it pronounced `eck-say`? `zay`? I don't know.

What would be nice:

> She (SHEE) went to the park.

OR:

> [... the current examples ...]
> # How to pronounce my he/him pronouns:
> he - HEE
> him - HIHM

IPA for English would be another option, although I find spelling-out more accessible.

Plural/singular could by specified in the database with an additional `\t[form]` for each declension of the pronoun on each line. If specifying non-in-database plurals, I propose this URL structure for "natural" structure:

    pronoun.is/zerg/rush?pronounced=ZRRG/ROOSH

reads "My pronoun is zerg/rush, and it's pronounced ZRRG/ROOSH"

I do not feel adequately prepared to use a neopronoun when I read the pronoun.is examples, because I don't know how to pronounce the pronouns. This is, in my opinion, a big problem.

I'd be happy to work on this, if this is considered a good idea.

**Comment by wakest** [comment]
this is a good idea and something I think is super useful necessary for adoption. It would even be quite useful to have a recording of the pronouns used in a sentence as well. could probably use the recordings from wikipedia/wiktionary or sources like that and have them embedded.

**Comment by morganastra** [comment]
I agree this would be a great feature to have, but there's not an obvious way to implement this right now.

See https://github.com/witch-house/pronoun.is#can-we-add-pronunciation-guides

**Comment by morganastra** [comment]
Issue #43 is also about this, we don't need two issues open
